# Experiment 9: Reasoning Model Benchmarking

## Objective

To compare the outputs of a reasoning model using different
prompting strategies and evaluate their effectiveness on
reasoning tasks.

## Prompting Strategies

1. Direct Prompt
2. Step-by-Step Prompt
3. Structured Prompt

## Workflow

Reasoning Problem
      ↓
Different Prompting Strategies
      ↓
Model Outputs
      ↓
Output Comparison
      ↓
Benchmark Results

In [1]:
print("Reasoning Model Benchmarking")
print("Experiment 9")

Reasoning Model Benchmarking
Experiment 9

In [2]:
reasoning_problem = """
A store has 5 boxes.
Each box contains 12 pencils.
The store sells 18 pencils.
Then it receives 24 more pencils.

How many pencils does the store have now?
"""

print("Benchmark Problem:")
print(reasoning_problem)

Benchmark Problem:

A store has 5 boxes.
Each box contains 12 pencils.
The store sells 18 pencils.
Then it receives 24 more pencils.

How many pencils does the store have now?

In [3]:
direct_prompt = f"""
{reasoning_problem}

Give the final answer.
"""

print("Direct Prompt:")
print(direct_prompt)

Direct Prompt:


A store has 5 boxes.
Each box contains 12 pencils.
The store sells 18 pencils.
Then it receives 24 more pencils.

How many pencils does the store have now?


Give the final answer.

In [4]:
step_by_step_prompt = f"""
Solve the following problem step by step.

Show the calculation at each step, then provide the final answer.

Problem:
{reasoning_problem}
"""

print("Step-by-Step Prompt:")
print(step_by_step_prompt)

Step-by-Step Prompt:

Solve the following problem step by step.

Show the calculation at each step, then provide the final answer.

Problem:

A store has 5 boxes.
Each box contains 12 pencils.
The store sells 18 pencils.
Then it receives 24 more pencils.

How many pencils does the store have now?

In [5]:
structured_prompt = f"""
Solve the following reasoning problem using this structure:

1. Identify the important information.
2. Perform the calculations.
3. Verify the result.
4. Give the final answer clearly.

Problem:
{reasoning_problem}
"""

print("Structured Prompt:")
print(structured_prompt)

Structured Prompt:

Solve the following reasoning problem using this structure:

1. Identify the important information.
2. Perform the calculations.
3. Verify the result.
4. Give the final answer clearly.

Problem:

A store has 5 boxes.
Each box contains 12 pencils.
The store sells 18 pencils.
Then it receives 24 more pencils.

How many pencils does the store have now?

In [6]:
!pip -q install transformers sentencepiece

In [7]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "google/flan-t5-base"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

print("Reasoning model loaded successfully!")

config.json:   0%|          | 0.00/1.40k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.54k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

spiece.model: reconstructing file:   0%|          |  0.00B /  792kB

spiece.model: downloading bytes:           |  0.00B

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  990MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/282 [00:00<?, ?it/s]

[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Reasoning model loaded successfully!

In [8]:
def run_model(prompt):
    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True
    )

    outputs = model.generate(
        **inputs,
        max_new_tokens=100
    )

    answer = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )

    return answer

print("Model function created successfully!")

Model function created successfully!

In [9]:
direct_output = run_model(direct_prompt)

print("Direct Prompt Output:")
print(direct_output)

Direct Prompt Output:
The store has 5 boxes * 12 pencils / box = 96 pencils. The store sells 18 pencils - 24 pencils = 24 pencils. The store has 96 pencils + 24 pencils = 108 pencils. The final answer: 108.

In [10]:
step_by_step_output = run_model(step_by_step_prompt)

print("Step-by-Step Prompt Output:")
print(step_by_step_output)

Step-by-Step Prompt Output:
The store has 5 boxes * 12 pencils / box = 96 pencils. The store sells 18 pencils - 24 pencils = 24 pencils. The store has 96 pencils + 24 pencils = 108 pencils. The final answer: 108.

In [11]:
structured_output = run_model(structured_prompt)

print("Structured Prompt Output:")
print(structured_output)

Structured Prompt Output:
The store has 5 boxes * 12 pencils / box = 96 pencils. The store sells 18 pencils - 24 pencils = 24 pencils. The store has 96 pencils + 24 pencils = 108 pencils. The final answer: 108.

In [12]:
print("=" * 60)
print("REASONING MODEL BENCHMARK RESULTS")
print("=" * 60)

print("\n1. DIRECT PROMPT")
print(direct_output)

print("\n2. STEP-BY-STEP PROMPT")
print(step_by_step_output)

print("\n3. STRUCTURED PROMPT")
print(structured_output)

============================================================
REASONING MODEL BENCHMARK RESULTS
============================================================

1. DIRECT PROMPT
The store has 5 boxes * 12 pencils / box = 96 pencils. The store sells 18 pencils - 24 pencils = 24 pencils. The store has 96 pencils + 24 pencils = 108 pencils. The final answer: 108.

2. STEP-BY-STEP PROMPT
The store has 5 boxes * 12 pencils / box = 96 pencils. The store sells 18 pencils - 24 pencils = 24 pencils. The store has 96 pencils + 24 pencils = 108 pencils. The final answer: 108.

3. STRUCTURED PROMPT
The store has 5 boxes * 12 pencils / box = 96 pencils. The store sells 18 pencils - 24 pencils = 24 pencils. The store has 96 pencils + 24 pencils = 108 pencils. The final answer: 108.

In [13]:
benchmark_results = {
    "Prompt Strategy": [
        "Direct Prompt",
        "Step-by-Step Prompt",
        "Structured Prompt"
    ],
    "Model Output": [
        direct_output,
        step_by_step_output,
        structured_output
    ]
}

import pandas as pd

benchmark_df = pd.DataFrame(benchmark_results)

display(benchmark_df)

       Prompt Strategy                                       Model Output
0        Direct Prompt  The store has 5 boxes * 12 pencils / box = 96 ...
1  Step-by-Step Prompt  The store has 5 boxes * 12 pencils / box = 96 ...
2    Structured Prompt  The store has 5 boxes * 12 pencils / box = 96 ...

In [14]:
id="expected_answer"
expected_answer = 66

print("Expected Answer:", expected_answer)

Expected Answer: 66

In [15]:
def check_answer(output, expected_answer):
    return str(expected_answer) in output

evaluation_results = {
    "Prompt Strategy": [
        "Direct Prompt",
        "Step-by-Step Prompt",
        "Structured Prompt"
    ],
    "Correct Answer Found": [
        check_answer(direct_output, expected_answer),
        check_answer(step_by_step_output, expected_answer),
        check_answer(structured_output, expected_answer)
    ]
}

evaluation_df = pd.DataFrame(evaluation_results)

display(evaluation_df)

       Prompt Strategy  Correct Answer Found
0        Direct Prompt                 False
1  Step-by-Step Prompt                 False
2    Structured Prompt                 False

In [16]:
print("=" * 60)
print("BENCHMARK SUMMARY")
print("=" * 60)

for strategy, correct in zip(
    evaluation_results["Prompt Strategy"],
    evaluation_results["Correct Answer Found"]
):
    status = "Correct" if correct else "Incorrect"
    print(f"{strategy}: {status}")

============================================================
BENCHMARK SUMMARY
============================================================
Direct Prompt: Incorrect
Step-by-Step Prompt: Incorrect
Structured Prompt: Incorrect

In [18]:
accuracy = (
    sum(evaluation_results["Correct Answer Found"])
    / len(evaluation_results["Correct Answer Found"])
) * 100

print(f"Overall Benchmark Accuracy: {accuracy:.2f}%")

Overall Benchmark Accuracy: 0.00%

# Experiment 9: Reasoning Model Benchmarking

## Objective

To compare the outputs of a reasoning model using different
prompting strategies and evaluate their effectiveness.

## Prompting Strategies

1. Direct Prompt
2. Step-by-Step Prompt
3. Structured Prompt

## Benchmark Problem

A store has 5 boxes. Each box contains 12 pencils.
The store sells 18 pencils and then receives 24 more pencils.

Expected Answer: 66 pencils.

## Result

The same model was tested using three different prompting strategies.
The outputs were compared with the expected answer.

## Conclusion

Different prompting strategies can influence how a model solves
and presents reasoning problems. Direct prompting provides a simple
baseline, while step-by-step and structured prompts provide more
explicit guidance for solving the problem.

The experiment demonstrates how prompt design can be used to
benchmark and compare model reasoning behavior.